### ISSUE TITLE
Intel integrated GPU only show up when btop is run by root (either by logging in or su or sudo).

### ISSUE THREAD

**Issue by Rajneesh315** [aristocratos/btop#1040]
https://github.com/user-attachments/assets/d08e6337-a873-48c5-910d-f9d539078cff

I have Thinkpad T490 with Nvidia mx250 dedicated gpu.
When btop is run by root user it detects both the GPUs, but when it is run by user _raj_ only the nvidia gpu is detected. 

- I tried copying the root's config, nothing changed .
- Switched between KDE and Xfce, still no change.

If btop is able to detect both the GPUs, why is only the nvidia one shown ?
Even simply running `sudo btop ` shows both the gpu.

**Comment by lane-ftw** [comment]
On my Proxmox system (Debian) I had to `sudo setcap cap_dac_read_search,cap_sys_admin+ep /usr/local/bin/btop` to get GPU to show up when not run as sudo.

**Comment by Rajneesh315** [comment]
> On my Proxmox system (Debian) I had to `sudo setcap cap_dac_read_search,cap_sys_admin+ep /usr/local/bin/btop` to get an Intel iGPU to show up when not run as sudo.

_Thank You for your reply and I am really sorry for the late reply, i got busy with college and other stuff._ 

For me `sudo setcap cap_dac_read_search,cap_sys_admin+ep /usr/bin/btop` this worked.  There was `btop` directory in `/usr/local/bin/`  .
I guess  we are elevating btop's privileges so that it can access restricted system data. 


Again Thank You and I apologize.

**Comment by lane-ftw** [comment]
Change `/usr/bin/btop` to your btop binary. Should be able to find it with `which btop`.

**Comment by lane-ftw** [comment]
>I guess we are elevating btop's privileges so that it can access restricted system data.
Pretty much
`cap_dac_read_search` allows btop to bypass file read permissions and directory search restrictions, meaning it can read files and search directories regardless of their permissions
`cap_sys_admin` allows the process to perform various system-level tasks like mounting filesystems, changing system settings, etc.
`+ep` stands for "effective" and "permitted" 
Permitted set: Contains capabilities that are available for use by the process, if allowed by the system.
Effective set: Contains the capabilities that are actually active and used by the process when it runs. It defines what the process can actually do.

**Comment by ErroneousBosch** [comment]
Can confirm I was havingthis same issue on Ubuntu 24.10. Solution from @Rajneesh315 fixed it.

**Comment by arthurl** [comment]
> On my Proxmox system (Debian) I had to `sudo setcap cap_dac_read_search,cap_sys_admin+ep /usr/local/bin/btop` to get an Intel iGPU to show up when not run as sudo.

That's way too much permission. You just need `cap_perfmon+ep`. This issue is already addressed in the makefile ([see line 363](https://github.com/aristocratos/btop/blob/v1.4.0/Makefile#L363)):

```make
#? Run setcap on btop for extended capabilities
setcap:
	@printf "\033[1;97mFile: $(DESTDIR)$(PREFIX)/bin/btop\n"
	@printf "\033[1;92mSetting capabilities...\033[0m\n"
	@setcap cap_perfmon=+ep $(DESTDIR)$(PREFIX)/bin/btop
```

**Comment by lane-ftw** [comment]
> > On my Proxmox system (Debian) I had to `sudo setcap cap_dac_read_search,cap_sys_admin+ep /usr/local/bin/btop` to get an Intel iGPU to show up when not run as sudo.
> 
> That's way too much permission. You just need `cap_perfmon+ep`. This issue is already addressed in the makefile ([see line 363](https://github.com/aristocratos/btop/blob/v1.4.0/Makefile#L363)):
> 
> #? Run setcap on btop for extended capabilities
> setcap:
> 	@printf "\033[1;97mFile: $(DESTDIR)$(PREFIX)/bin/btop\n"
> 	@printf "\033[1;92mSetting capabilities...\033[0m\n"
> 	@setcap cap_perfmon=+ep $(DESTDIR)$(PREFIX)/bin/btop

I just tried this, `sudo setcap -r /usr/local/bin/btop` `sudo setcap cap_perfmon=+ep /usr/local/bin/btop` and I still only get an iGPU output when run with sudo/root. Maybe I messed making btop?

**Comment by arthurl** [comment]
> I just tried this, `sudo setcap -r /usr/local/bin/btop` `sudo setcap cap_perfmon=+ep /usr/local/bin/btop` and I still only get an iGPU output when run with sudo/root. Maybe I messed making btop? EDIT: Turns out `cap_dac_read_search` isn't needed, but `cap_sys_admin` seems to be.

Strange, I just re-checked, and `setcap cap_perfmon+ep` only (without `cap_sys_admin`) worked for me.

**Comment by Meow0x7E** [comment]
My system is Arch Linux. On my system, I only need to run `sudo setcap cap_perfmon=ep /usr/bin/btop` to make sure that btop can display information about the Intel integrated graphics properly.

**Comment by rakklak** [comment]
Still having this issue as of today `setcap cap_sys_admin+ep /usr/local/bin/btop` had no effect and I am running as root on Proxmox 8.4

**Comment by jclsn** [comment]
@rakklak Then you are probably running an older version of btop. Check ``btop --version``!

**Comment by rakklak** [comment]
> [@rakklak](https://github.com/rakklak) Then you are probably running an older version of btop. Check `btop --version`!

I cloned directly from the git and did not use the package manager 
`btop version: 1.4.2`

**Comment by 0x70369** [comment]
Posting this question because I got curious: why does btop need this extra access with `sudo setcap cap_perfmon=ep /usr/bin/btop` to show the Intel iGPU stats, but not with a Nvidia dGPU? Why are they treated differently?

**Comment by DoTheEvo** [comment]
commenting that yeah, confirming that setcap makes it work for me
`sudo setcap cap_sys_admin+ep "$(which btop)"`

**Comment by matthane** [comment]
I can also confirm with the above that the GPU stat is only visible when cap_sys_admin+ep is used. None of the other capabilities seem to work. I'm using an Intel N150 processor with Ubuntu server.

**Comment by ItsLiyua** [comment]
If anyone's looking into this for NixOS:
```nix
security.wrappers.btop = {
  enable = true;
  owner = "root";
  group = "root";
  source = "${pkg}/bin/btop";
  capabilities = "cap_perfmon=ep";
};
```
This works for me

**Comment by rakklak** [comment]
> > [@rakklak](https://github.com/rakklak) Then you are probably running an older version of btop. Check `btop --version`!
> 
> I cloned directly from the git and did not use the package manager `btop version: 1.4.2`

Cloned 1.4.3 and it resolved my issues

**Comment by arthurl** [comment]
> If anyone's looking into this for NixOS:
> 
> security.wrappers.btop = {
>   enable = true;
>   owner = "root";
>   group = "root";
>   source = "${pkg}/bin/btop";
>   capabilities = "cap_perfmon=ep";
> };
> 
> This works for me

FYI you don't need the "enable" attribute.

**Comment by ItsLiyua** [comment]
Yeah I know. That was just left over from debugging. Thanks for telling me tho :D

**Comment by daryltucker** [comment]
Excited to see when Debian can use `cap_sys_admin+ep` and NOT `cap_sys_admin+ep`.

I confirmed on `6.12.48+deb13-amd64` `cap_perfmon=ep` is not enough.  You either must use root/`sudo`, or `cap_sys_admin+ep`.
I did this for testing and have removed such permissions as I see this as too much of a risk.

What's kind of crazy to me is I already have a group, `procview`, gid:47, and users of that group can see all system processes:
```bash
proc                                            /proc           proc    defaults,hidepid=2,gid=47       0       0
```

but maybe you guys use `perf_event_open` or something.

Either way, even with `log_level = "DEBUG"`, I don't see any hints of any issues or any ways I can troubleshoot any further.


```bash
$ btop --version
btop version: 1.4.5+7c29dc0
Compiled with: g++ (11.4.0)
Configured with: make STATIC= GPU_SUPPORT=true RSMI_STATIC=
```

**Comment by ottok** [comment]
This is tracked for Debian/Ubuntu at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1121422

**Comment by GrassGlass** [comment]
`setcap` changes don't persist when a file is removed, so `btop` stops showing GPU stats on upgrade (e.g. `sudo dnf upgrade`) when run as a non-root user. Here is a solution for systems whose package manager is DNF. 

If we're running DNF5, we can install `dnf5-plugin-actions` ([documentation](https://dnf5.readthedocs.io/en/latest/libdnf5_plugins/actions.8.html)) and write the file `/etc/dnf/libdnf5-plugins/actions.d/btop.actions` with contents
```
# Give `btop` sufficient permissions to access GPU information to be displayed
# https://github.com/aristocratos/btop/issues/1040#issuecomment-2733179974
post_transaction:btop:in::setcap cap_perfmon=+ep /usr/bin/btop
```
For DNF4, we can do something similar with `dnf-plugins-core` ([documentation](https://dnf-plugins-core.readthedocs.io/en/latest/)).

For Debian based systems, [`apt.conf`](https://linux.die.net/man/5/apt.conf) seems to offer similar functionalities, though I haven't read deep into it.
